### ISSUE TITLE
Infografía sobre la Construcción del Conocimiento 

### ISSUE THREAD

**Issue by Daniel-Velasco-Lopez** [SistemasTecTlaxiaco/actividad-2-infografia-Daniel-Velasco-Lopez#1]
Daniel Velasco López           1°BS
Construcción del conocimiento 

![png_20220830_223711_0000](https://user-images.githubusercontent.com/112217987/187588420-5c937541-869a-42f4-9961-1c40024c7015.png)

**Comment by YaelTrinidad** [comment]
ACTIVIDAD 2 INFOGRAFIA
DE 20% DE LA ACTIVIDAD OBTUVISTE 17.2% DE ACUERDO A LA RUBRICA

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
